# use python 3.10 alpine as base image
FROM python:3.10-alpine

# set container working/context directory
WORKDIR /app

# copy source code and requirements from src to container working directory
COPY . .

# install all dependencies
RUN pip3 install -r requirements.txt

# expose port 80
EXPOSE 80

# run the application
CMD ["python3", "src/app.py"]
