version: "3.9"


services:
  redis:
    image: bitnami/redis:7.0.11
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data
    networks:
      - app-tier

  web:
    image: docker-ws:2.0  
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 8080:80
    networks:
      - app-tier
    depends_on:
      - redis


volumes:
  redis-data:


networks:
  app-tier:
    driver: bridge # default
